// This is the final version of the LLM-generated equivalent of the Create Markup Script.
// The script below was generated by LLM first and then edited and refactored by hand.
// Prior to editing / refactoring, the script below was 131 lines.
// After editing / refactoring, the script below is 63 lines.
//
// This entire process took:
// Four seconds to generate
// Four minutes to tidy up
// Six minutes to debug (two approaches, neither worked)
// Two minutes to vibe-debug (successfully)
// Two minutes to check
// Ten minutes to read, cognitively dissect and understand the generated code
// Having substantially understood the generated code, sixteen more minutes tidying it up / refactoring it
// Finally: twenty minutes to study / re-engineer / re-write an idiosyncratic and convoluted setup involving a single-use function parameter


// 63 LINES
function htmlToJavaScript(html, elementParent = 'document.body') {
  const parser = new DOMParser();
  const document = parser.parseFromString(`<div id='__html_to_js__'>${html}</div>`, 'text/html');

  let elementCounter = 0;
  const lines = [];
  const isValidDatasetProperty = (property) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(property);

  function dataAttributeToDatasetProperty(attribute) {
    return attribute
      .slice(5)
      .split('-')
      .map((part, index) => ((index === 0) ? part : part.charAt(0).toUpperCase() + part.slice(1)))
      .join('');
  }

  function emitAttribute(element, attribute) {
    switch (true) {
      case (attribute.name === 'class'):
        const classes = attribute.value.match(/\S+/g) || [];
        classes.forEach((className) => lines.push(`${element}.classList.add(${JSON.stringify(className)});`));
      break;

      case (attribute.name === 'id'):
        lines.push(`${element}.id = ${JSON.stringify(attribute.value)};`);
      break;

      case (attribute.name.startsWith('data-')):
        const property = dataAttributeToDatasetProperty(attribute.name);
        (isValidDatasetProperty(property))
          ? lines.push(`${element}.dataset.${property} = ${JSON.stringify(attribute.value)};`)
          : lines.push(`${element}.setAttribute(${JSON.stringify(attribute.name)}, ${JSON.stringify(attribute.value)});`);
      break;

      default: lines.push(`${element}.setAttribute(${JSON.stringify(attribute.name)}, ${JSON.stringify(attribute.value)});`);
    }
  }

  function emitNode(node, elementParent) {
    switch (node.nodeType) {
      case (Node.ELEMENT_NODE):
        elementCounter++;
        const element = `el${elementCounter}`;
        lines.push(`const ${element} = document.createElement(${JSON.stringify(node.tagName.toLowerCase())});`);
        [...node.attributes].forEach((attribute) => emitAttribute(element, attribute));
        lines.push(`${elementParent}.appendChild(${element});`);
        [...node.childNodes].forEach((childNode) => emitNode(childNode, element));
      break;

      case (Node.TEXT_NODE):
        if (node.nodeValue !== '') {
          lines.push(`${elementParent}.appendChild(document.createTextNode(${JSON.stringify(node.nodeValue)}));`);
        }
      break;

      case (Node.COMMENT_NODE):
        lines.push(`${elementParent}.appendChild(document.createComment(${JSON.stringify(node.nodeValue)}));`);
      break;
    }
  }

  document.body.childNodes.forEach((childNode) => emitNode(childNode, elementParent));
  return lines.join("\n").replaceAll('\"', '`');
}


// MARKUP
let markup = `
  <header class="header">
    <h1 class="pageHeading">My Main Heading</h1>
    <img class="pageLogo" src="/path/to/page-logo.png" />
  </header>

  <main class="main">  
   <h2 class="mainHeading">My Subheading</h2>
   <p class="mainParagraph">This is a paragraph.</p>
   <p class="mainParagraph">This is <em class="emphasisedText">another</em> paragraph.</p>
   <p class="mainParagraph">This is <em class="emphasisedText"><b class="boldText">a third</b></em> paragraph.</p>
   <p class="mainParagraph" hidden>This is a hidden fourth paragraph.</p>
  </main>


  <footer id="footer" class="footer">
    <nav class="footerNav">
      <ul class="footerButtonList">
        <li class="footerButtonListItem"><button class="footerButton --about" type="button" data-lock-setting="unlocked">About</button></li>
        <li class="footerButtonListItem"><button class="footerButton --demos" type="button" data-lock-setting="locked" disabled>Demos</button></li>
        <li class="footerButtonListItem"><button class="footerButton --credits" type="button" data-lock-setting="unlocked">Credits</button></li>
      </ul>
    </nav> 
  </footer>
`;


// RUN FUNCTION
console.log('Markup: ', htmlToJavaScript(markup));
